account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import (
ArticleList,
ArticleCreate,
ArticleUpdate,
ArticleDelete,
Profile,
)

app_name = "account"


urlpatterns = [
    path('', ArticleList.as_view(),name="home"),
    path("article/create", ArticleCreate.as_view(), name="article-create"),
    path('article/update/<int:pk>', ArticleUpdate.as_view(), name="article-update"),
    path('article/delete/<int:pk>', ArticleDelete.as_view(), name="article-delete"),
    path('profile/', Profile.as_view(), name="profile"),
]

posts/urls.py
from django.urls import path, include
from django.conf import settings
from .views import (
    ArticleList,
    ArticleDetail,
    about,
    CategoryList,
    AuthorList,
    ArticlePreview,
    SearchList,
)
app_name="blog"
urlpatterns = [
# path('page/<int:page>', home, name='home'),
path('', ArticleList.as_view(), name='home'),
path('page/<int:page>', ArticleList.as_view(), name='home'),
path('article/<slug:slug>/', ArticleDetail.as_view(), name='detail'),
path('preview/<int:pk>/', ArticlePreview.as_view(), name='preview'),
path('about.html',about,name='about'),
path('category/<slug:slug>/', CategoryList.as_view(), name='category'),
path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name='category'),
path('author/<slug:username>/', AuthorList.as_view(), name='author'),
path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name='author'),
path('search/', SearchList.as_view(), name='search'),
path('search/page/<int:page>', SearchList.as_view(), name='search'),
    ]

pr2/urls.py
from Scripts.activate_this import lib
# from account import views
from django.contrib import admin
from account.views import ArticleList,ArticleCreate
from django.urls import path,include, re_path
from posts.views import ArticleList,ArticleDetail,CategoryList,Article
from django.conf import settings
from account.views import Login, Register, activate
app_name = "post"
urlpatterns = [

    path('',include('posts.urls')),
    path('', include('django.contrib.auth.urls')),
    path("login/", Login.as_view(), name="login"),
    path("register/", Register.as_view(), name="register"),
    # url(r'^signup/$', views.signup, name='signup'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$', activate, name='activate'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    # path('account/',ArticleList.as_view()),
    path("article/create", ArticleCreate.as_view(), name="article-create"),
    path('comment/', include('comment.urls')),
]
# from django.conf.urls.static import static
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/article_list.html
{% extends 'list.html' %}

{% block header %}

{% endblock %}

{% block next_page_url %}
    {% url 'blog:home' page_obj.next_page_number  %}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}
{#{% load static %}#}
{##}
{#{% block main %}#}
{#            <!-- Page Header-->#}
{#        <header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">#}
{#            <div class="container position-relative px-4 px-lg-5">#}
{#                <div class="row gx-4 gx-lg-5 justify-content-center">#}
{#                    <div class="col-md-10 col-lg-8 col-xl-7">#}
{#                        <div class="site-heading">#}
{#                            <h1>فروشگاه من </h1>#}
{#                            <span class="subheading">A Blog Theme by Start Bootstrap</span>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </header>#}
{#        <div class="container px-4 px-lg-5">#}
{#            <div class="row gx-4 gx-lg-5 justify-content-center">#}
{#                <div class="col-md-10 col-lg-8 col-xl-7">#}
{##}
{#                    <!-- Post preview-->#}
{#                {% for article in articles %}#}
{#                    اینجا جای article میتونستیم بذاریم object_list وقتی از کلاس بیس استفاده میکنیم#}
{#                    <div class="post-preview">#}
{#                        <a href="{% url 'blog:detail' article.slug %}">#}
{#                            <h2 class="post-title">{{ article.title }}</h2>#}
{#                            <h3 class="post-subtitle">{{ article.description|truncatewords:30 }}</h3>#}
{#                        </a>#}
{#                        <p class="post-meta">#}
{#                            نوشته شده توسط#}
{#                            <a href="#!">کلبه رنگین</a>#}
{#                            {{ article.jpublish }}#}
{#                        </p>#}
{#                        <div>#}
{#                            {% for cat in article.category.active %}#}
{##}
{#                                <a href="{% url 'blog:category' cat.slug %}">#{{ cat.title }}</a>#}
{#                            {% endfor %}#}
{#                        </div>#}
{#                    </div>#}
{#                    <!-- Divider-->#}
{#                        <hr class="my-4" />#}
{#                {% endfor %}#}
{#                    <!-- Pager-->#}
{#                    {% if is_paginated %}#}
{#                        <div class="clearfix pager-button">#}
{#                        {% if page_obj.has_next %}#}
{#                            <div class="d-flex justify-content-end mb-4 pager-button"><a class="btn btn-primary text-uppercase m-lg-2" href="{% block next_page_url %}{% endblock %}"> پست های قدیمی &lAarr;</a></div>#}
{#                        {% endif %}#}
{#                        {% if page_obj.has_previous %}#}
{#                            <div class="d-flex justify-content-end mb-4 pager-button"><a class="btn btn-primary text-uppercase m-lg-2" href="{% block previous_page_url %}{% endblock %}">  &rAarr; پست های جدید</a></div>#}
{#                        {% endif %}#}
{#                    {% endif %}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        </div>#}
{#{% endblock %}#}

templates/author_list.html
{% extends 'list.html' %}
{% block header %}
    <h3 class="alert alert-primary text-center">نویسنده: {{ author.get_full_name }}</h3>
{% endblock %}

{% block next_page_url %}
    {% url 'blog:author' author.username page_obj.next_page_number  %}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

templates/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
{#    {% block title %}#}
{##}
{#    {% endblock %}#}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>mmli</title>
        <link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
{#        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />#}
{#        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />#}
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href=" {% static 'blog/css/rtl2.css' %}" rel="stylesheet" />
            {#        star rating statics #}
        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
{#                <a class="navbar-brand" href="{% url 'account:home' %}">حساب کاربری</a>#}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>

        <!-- Main Content-->
{% block main %}

{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/category.html
{% extends 'list.html' %}
{% block header %}
    <h3 class="alert alert-primary text-center">دستی بندی: {{ category.title }}</h3>
{% endblock %}

{% block next_page_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number  %}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% load comment_tags %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}
{# Render all the comments belong to the passed object "obj" #}

{% block title %} | {{ article.title }}
{#اینجا هایی که از article یه چیزی گرفتیم در اضل باید میذاشتیم object ولی تو لیست ویو باید بنویسیم object_list #}
{% endblock %}

{% block main %}

            <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{ article.thumbnail.url }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{ article.title }}</h1>
                            {% if article.is_special %}
                                <span style="background-color: red;color: white;font-size: 24px">ویژه</span>
                            {% endif %}
                            <time>{{ article.published|naturaltime }}</time>
                        <div>{% ratings object %}</div>
                        <div>بازدید ها: {{ object.hits.count }}</div>
{#                            <span class="subheading">A Blog Theme by Start Bootstrap</span>#}
                        </div>
                    </div>
                </div>
            </div>
        </header>
<!-- Post Content-->
                <aside>
                    {% hot_articles %}
                    {% popular_articles %}
                </aside>
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">

                    <div class="col-md-10 col-lg-8 col-xl-7 text-justify">

                       {% if object.is_special %}
                       {% if user.is_athenticated and user.is_special_user or user == object.author or user.is_superuser %}
                           {{ article.description|safe }}
                           {% else %}
                           {{ article.description|striptags|truncatewords:30 }}
                           <p class="alert alert-warning">این مقاله ویژه است و برای مشاهد باید <a class="alert-link" href="#">اشتراک ویژه </a>خریداری کنید</p>
                           {% endif %}
                           {% else %}
                           {{ article.description|safe }}
                       {% endif %}

                        {% render_comments object request %}
                        {% include_static %}
                        {% include_bootstrap %}


                    </div>
                </div>
            </div>
        </article>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}
{% block main %}
            <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>فروشگاه من </h1>
{#                            <span class="subheading">A Blog Theme by Start Bootstrap</span>#}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                {% block header %} {% endblock %}
                <aside>
                {% hot_articles %}
                {% popular_articles %}
                </aside>

                    <!-- Post preview-->
                {% for article in object_list %}
                    <div class="post-preview">
                        <a href="{% url 'blog:detail' article.slug %}">

                            <h2 class="post-title">{{ article.title }}
                                {% if article.is_special %}
                                <span style="background-color: red;color: white;font-size: 24px">ویژه</span>
                            {% endif %}</h2>
                        {% ratings article %}

                            <h3 class="post-subtitle">{{ article.description|striptags|truncatewords:30 }}</h3>
                        </a>
                        <p class="post-meta">
                            نوشته شده توسط
                            <a href="{% url 'blog:author' article.author %}">{{ article.author.get_full_name}}</a>
                            {{ article.published|naturaltime }}
                        </p>
                        <div>
                            {% for cat in article.category.active %}

                                <a href="{% url 'blog:category' cat.slug %}">#{{ cat.title }}</a>
                            {% endfor %}
                        </div>
                    <div>بازدید ها: {{ article.hits.count }}</div>
                    </div>
                    <!-- Divider-->
                        <hr class="my-4" />
                    {% empty %}
                    <p>متاستفانه محتوایی برای نمایش وجود ندارد</p>
                {% endfor %}
                    <!-- Pager-->
                <div class="clearfix pager-button">
                {% if is_paginated %}
                    <div class="clearfix pager-button">
                    {% if page_obj.has_next %}
                        <div class="d-flex justify-content-end mb-4 pager-button"><a class="btn btn-primary text-uppercase m-lg-2" href="{% block next_page_url %}{% endblock %}"> پست های قدیمی &lAarr;</a></div>
                    {% endif %}
                    {% if page_obj.has_previous %}
                        <div class="d-flex justify-content-end mb-4 pager-button"><a class="btn btn-primary text-uppercase m-lg-2" href="{% block previous_page_url %}{% endblock %}">  &rAarr; پست های جدید</a></div>
                    {% endif %}
                {% endif %}
                </div>
            </div>
        </div>
        </div>
{% endblock %}

templates/search_list.html
{% extends 'list.html' %}
{% block header %}
    <h3 class="alert alert-primary text-center">جستجو: {{ search }}</h3>
{% endblock %}

{% block next_page_url %}
    {% url 'blog:search'  page_obj.next_page_number  %}?q={{ search }}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:search'  page_obj.previous_page_number %}?q={{ search }}
{% endblock %}